### ISSUE TITLE
Bad version declared

### ISSUE THREAD

**Issue by bcoutre** [pulumi/pulumi-kubernetes-cert-manager#14]
### What happened?

I tried to use the cert-manager plugin but it throw warnings : 
```
warning: resource plugin kubernetes-cert-manager is expected to have version >=0.0.3, but has 0.0.1; the wrong version may be on your path, or this may be a bug in the plugin
```

### Steps to reproduce

1. put the exemple with my own "settings" 
2. `npm install --save @pulumi/kubernetes-cert-manager`

3. run a `pulumi up`

### Expected Behavior

Use the correct version. 
I don't know if this is the reason why I can't get certs because I have not yet finished configuration.

### Actual Behavior

Seems to have the bad version

### Versions used

Version      3.35.3

### Additional context

no other details.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by bcoutre** [comment]
@stack72  
here is the version downloaded: `@pulumi/kubernetes-cert-manager: 0.0.3`
pulumi in the 3.35.3 
I use in TypeScript I don't know how to check for more recent version ?

**Comment by stack72** [comment]
Hi @bcoutre 

My apologies - we fixed a different provider that had this same error! I have just opened a PR that fixes it :)

Paul

**Comment by pcuci** [comment]
Hm, `pulumi plugin install --reinstall` seems to have fixed half the issue I had, i.e.: had two versions installed `0.0.1` and `0.0.3` - not sure how that came about (on a fresh pulumi install on a new machine)...

Still getting this warning:

``` bash
warning: resource plugin kubernetes-cert-manager is expected to have version >=0.0.3, but has 0.0.1; the wrong version may be on your path, or this may be a bug in the plugin
```

**Comment by JonAStorelv** [comment]
> 

This seem to still be a issue.
I'm using typescript and running pulumi 3.47.1

`warning: resource plugin kubernetes-cert-manager is expected to have version >=0.0.3, but has 0.0.1; the wrong version may be on your path, or this may be a bug in the plugin`
